# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created: Sun Feb 24 17:20:23 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_calculator(object):
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(376, 280)
        calculator.setMinimumSize(QtCore.QSize(376, 280))
        calculator.setMaximumSize(QtCore.QSize(376, 280))
        self.centralWidget = QtGui.QWidget(calculator)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_7.setMinimumSize(QtCore.QSize(85, 32))
        self.button_7.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_7.setFont(font)
        self.button_7.setStyleSheet("background-color: #ECECEC;")
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 4, 0, 1, 1)
        self.button_8 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_8.setMinimumSize(QtCore.QSize(85, 32))
        self.button_8.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_8.setFont(font)
        self.button_8.setStyleSheet("background-color: #ECECEC;")
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 4, 1, 1, 1)
        self.button_5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_5.setMinimumSize(QtCore.QSize(85, 32))
        self.button_5.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_5.setFont(font)
        self.button_5.setStyleSheet("background-color: #ECECEC;")
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 5, 1, 1, 1)
        self.button_minus = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_minus.setMinimumSize(QtCore.QSize(85, 32))
        self.button_minus.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_minus.setFont(font)
        self.button_minus.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_minus.setObjectName("button_minus")
        self.gridLayout.addWidget(self.button_minus, 7, 3, 1, 1)
        self.button_3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_3.setMinimumSize(QtCore.QSize(85, 32))
        self.button_3.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_3.setFont(font)
        self.button_3.setStyleSheet("background-color: #ECECEC;")
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 7, 2, 1, 1)
        self.button_ce = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_ce.setMinimumSize(QtCore.QSize(85, 32))
        self.button_ce.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_ce.setFont(font)
        self.button_ce.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_ce.setObjectName("button_ce")
        self.gridLayout.addWidget(self.button_ce, 3, 3, 1, 1)
        self.button_4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_4.setMinimumSize(QtCore.QSize(85, 32))
        self.button_4.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_4.setFont(font)
        self.button_4.setStyleSheet("background-color: #ECECEC;")
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 5, 0, 1, 1)
        self.button_plus = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_plus.setMinimumSize(QtCore.QSize(85, 32))
        self.button_plus.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_plus.setFont(font)
        self.button_plus.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_plus.setObjectName("button_plus")
        self.gridLayout.addWidget(self.button_plus, 8, 3, 1, 1)
        self.button_multiply = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_multiply.setMinimumSize(QtCore.QSize(85, 32))
        self.button_multiply.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_multiply.setFont(font)
        self.button_multiply.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_multiply.setObjectName("button_multiply")
        self.gridLayout.addWidget(self.button_multiply, 5, 3, 1, 1)
        self.button_divide = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_divide.setMinimumSize(QtCore.QSize(85, 32))
        self.button_divide.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_divide.setFont(font)
        self.button_divide.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_divide.setObjectName("button_divide")
        self.gridLayout.addWidget(self.button_divide, 4, 3, 1, 1)
        self.button_power = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_power.setMinimumSize(QtCore.QSize(85, 32))
        self.button_power.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_power.setFont(font)
        self.button_power.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_power.setObjectName("button_power")
        self.gridLayout.addWidget(self.button_power, 3, 1, 1, 1)
        self.button_equal = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_equal.setMinimumSize(QtCore.QSize(85, 32))
        self.button_equal.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_equal.setFont(font)
        self.button_equal.setStyleSheet("color: #fff;\n"
"background-color: #608BCC;" "border: none;")
        self.button_equal.setObjectName("button_equal")
        self.gridLayout.addWidget(self.button_equal, 8, 2, 1, 1)
        self.button_sqrt = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_sqrt.setMinimumSize(QtCore.QSize(85, 32))
        self.button_sqrt.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_sqrt.setFont(font)
        self.button_sqrt.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_sqrt.setObjectName("button_sqrt")
        self.gridLayout.addWidget(self.button_sqrt, 3, 0, 1, 1)
        self.button_2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_2.setMinimumSize(QtCore.QSize(85, 32))
        self.button_2.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_2.setFont(font)
        self.button_2.setStyleSheet("background-color: #ECECEC;")
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 7, 1, 1, 1)
        self.button_0 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_0.setMinimumSize(QtCore.QSize(85, 32))
        self.button_0.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_0.setFont(font)
        self.button_0.setStyleSheet("background-color: #ECECEC;")
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 8, 0, 1, 1)
        self.button_1 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy)
        self.button_1.setMinimumSize(QtCore.QSize(85, 32))
        self.button_1.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_1.setFont(font)
        self.button_1.setStyleSheet("background-color: #ECECEC;")
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 7, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 4)
        self.button_6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_6.setMinimumSize(QtCore.QSize(85, 32))
        self.button_6.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_6.setFont(font)
        self.button_6.setStyleSheet("background-color: #ECECEC;")
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 5, 2, 1, 1)
        self.button_dot = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_dot.setMinimumSize(QtCore.QSize(85, 32))
        self.button_dot.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_dot.setFont(font)
        self.button_dot.setStyleSheet("background-color: #ECECEC;")
        self.button_dot.setObjectName("button_dot")
        self.gridLayout.addWidget(self.button_dot, 8, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(358, 32))
        self.lineEdit.setMaximumSize(QtCore.QSize(356, 32))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtCore.Qt.BlankCursor)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 4)
        self.button_sign = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_sign.setMinimumSize(QtCore.QSize(85, 32))
        self.button_sign.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_sign.setFont(font)
        self.button_sign.setStyleSheet("color: #fff;\n"
"background-color: #AAB3B6;" "border: none;")
        self.button_sign.setObjectName("button_sign")
        self.gridLayout.addWidget(self.button_sign, 3, 2, 1, 1)
        self.button_9 = QtGui.QPushButton(self.gridLayoutWidget)
        self.button_9.setMinimumSize(QtCore.QSize(85, 32))
        self.button_9.setMaximumSize(QtCore.QSize(85, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.button_9.setFont(font)
        self.button_9.setStyleSheet("background-color: #ECECEC;")
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 4, 2, 1, 1)
        calculator.setCentralWidget(self.centralWidget)

        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)

    def retranslateUi(self, calculator):
        calculator.setWindowTitle(QtGui.QApplication.translate("calculator", "Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.button_7.setText(QtGui.QApplication.translate("calculator", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.button_8.setText(QtGui.QApplication.translate("calculator", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.button_5.setText(QtGui.QApplication.translate("calculator", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.button_minus.setText(QtGui.QApplication.translate("calculator", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_3.setText(QtGui.QApplication.translate("calculator", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.button_ce.setText(QtGui.QApplication.translate("calculator", "CE", None, QtGui.QApplication.UnicodeUTF8))
        self.button_4.setText(QtGui.QApplication.translate("calculator", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.button_plus.setText(QtGui.QApplication.translate("calculator", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.button_multiply.setText(QtGui.QApplication.translate("calculator", "×", None, QtGui.QApplication.UnicodeUTF8))
        self.button_divide.setText(QtGui.QApplication.translate("calculator", "÷", None, QtGui.QApplication.UnicodeUTF8))
        self.button_power.setText(QtGui.QApplication.translate("calculator", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.button_equal.setText(QtGui.QApplication.translate("calculator", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.button_sqrt.setText(QtGui.QApplication.translate("calculator", "√", None, QtGui.QApplication.UnicodeUTF8))
        self.button_2.setText(QtGui.QApplication.translate("calculator", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.button_0.setText(QtGui.QApplication.translate("calculator", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_1.setText(QtGui.QApplication.translate("calculator", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.button_6.setText(QtGui.QApplication.translate("calculator", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.button_dot.setText(QtGui.QApplication.translate("calculator", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.button_sign.setText(QtGui.QApplication.translate("calculator", "+/-", None, QtGui.QApplication.UnicodeUTF8))
        self.button_9.setText(QtGui.QApplication.translate("calculator", "9", None, QtGui.QApplication.UnicodeUTF8))

